/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculadoraSimple;

/**
 *
 * @author Emma
 */
public class FRMCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form FRMCalculadora
     */
    public FRMCalculadora() {
        initComponents();
    }
    Calculadora objCalculadora = new Calculadora();
    String cero = "0";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DosBTN = new javax.swing.JButton();
        TresBTN = new javax.swing.JButton();
        SumarBTN = new javax.swing.JButton();
        CuatroBTN = new javax.swing.JButton();
        CincoBTN = new javax.swing.JButton();
        SeisBTN = new javax.swing.JButton();
        RestarBTN = new javax.swing.JButton();
        SieteBTN = new javax.swing.JButton();
        UnoBTN = new javax.swing.JButton();
        OchoBTN = new javax.swing.JButton();
        MultiplicarBTN = new javax.swing.JButton();
        NueveBTN = new javax.swing.JButton();
        PuntoBTN = new javax.swing.JButton();
        IgualBTN = new javax.swing.JButton();
        CeroBTN = new javax.swing.JButton();
        DividirBTN = new javax.swing.JButton();
        ResultadoTXT = new javax.swing.JTextField();
        BorrarBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        DosBTN.setText("2");
        DosBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        DosBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DosBTNMouseClicked(evt);
            }
        });

        TresBTN.setText("3");
        TresBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        TresBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TresBTNMouseClicked(evt);
            }
        });

        SumarBTN.setText("+");
        SumarBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        SumarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumarBTNMouseClicked(evt);
            }
        });

        CuatroBTN.setText("4");
        CuatroBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        CuatroBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CuatroBTNMouseClicked(evt);
            }
        });

        CincoBTN.setText("5");
        CincoBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        CincoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CincoBTNMouseClicked(evt);
            }
        });

        SeisBTN.setText("6");
        SeisBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        SeisBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeisBTNMouseClicked(evt);
            }
        });

        RestarBTN.setText("-");
        RestarBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        RestarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestarBTNMouseClicked(evt);
            }
        });

        SieteBTN.setText("7");
        SieteBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        SieteBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SieteBTNMouseClicked(evt);
            }
        });

        UnoBTN.setText("1");
        UnoBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        UnoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UnoBTNMouseClicked(evt);
            }
        });

        OchoBTN.setText("8");
        OchoBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        OchoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OchoBTNMouseClicked(evt);
            }
        });

        MultiplicarBTN.setText("*");
        MultiplicarBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        MultiplicarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MultiplicarBTNMouseClicked(evt);
            }
        });

        NueveBTN.setText("9");
        NueveBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        NueveBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NueveBTNMouseClicked(evt);
            }
        });

        PuntoBTN.setText(".");
        PuntoBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        PuntoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PuntoBTNMouseClicked(evt);
            }
        });

        IgualBTN.setText("=");
        IgualBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        IgualBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IgualBTNMouseClicked(evt);
            }
        });

        CeroBTN.setText("0");
        CeroBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        CeroBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CeroBTNMouseClicked(evt);
            }
        });

        DividirBTN.setText("/");
        DividirBTN.setPreferredSize(new java.awt.Dimension(47, 41));
        DividirBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DividirBTNMouseClicked(evt);
            }
        });

        BorrarBTN.setText("CE");
        BorrarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrarBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CuatroBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CincoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeisBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RestarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UnoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TresBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SumarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SieteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OchoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NueveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MultiplicarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CeroBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PuntoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IgualBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DividirBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ResultadoTXT)
                    .addComponent(BorrarBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ResultadoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DosBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TresBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SumarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuatroBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CincoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeisBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SieteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OchoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NueveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiplicarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CeroBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PuntoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IgualBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DividirBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BorrarBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnoBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("1"));
    }//GEN-LAST:event_UnoBTNMouseClicked

    private void DosBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DosBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("2"));
    }//GEN-LAST:event_DosBTNMouseClicked

    private void TresBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TresBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("3"));
    }//GEN-LAST:event_TresBTNMouseClicked

    private void CuatroBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CuatroBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("4"));
    }//GEN-LAST:event_CuatroBTNMouseClicked

    private void CincoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CincoBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("5"));
    }//GEN-LAST:event_CincoBTNMouseClicked

    private void SeisBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeisBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("6"));
    }//GEN-LAST:event_SeisBTNMouseClicked

    private void SieteBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SieteBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("7"));
    }//GEN-LAST:event_SieteBTNMouseClicked

    private void OchoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OchoBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("8"));
    }//GEN-LAST:event_OchoBTNMouseClicked

    private void NueveBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NueveBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("9"));
    }//GEN-LAST:event_NueveBTNMouseClicked

    private void CeroBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CeroBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("0"));
    }//GEN-LAST:event_CeroBTNMouseClicked

    private void PuntoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PuntoBTNMouseClicked
        ResultadoTXT.setText(objCalculadora.Concatenamiento("."));
    }//GEN-LAST:event_PuntoBTNMouseClicked

    private void SumarBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumarBTNMouseClicked
        objCalculadora.Suma(ResultadoTXT.getText());
    }//GEN-LAST:event_SumarBTNMouseClicked

    private void RestarBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestarBTNMouseClicked
        objCalculadora.Resta(ResultadoTXT.getText());
    }//GEN-LAST:event_RestarBTNMouseClicked

    private void MultiplicarBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplicarBTNMouseClicked
        objCalculadora.Multiplicacion(ResultadoTXT.getText());
    }//GEN-LAST:event_MultiplicarBTNMouseClicked

    private void DividirBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DividirBTNMouseClicked
        objCalculadora.Division(ResultadoTXT.getText());
    }//GEN-LAST:event_DividirBTNMouseClicked

    private void IgualBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IgualBTNMouseClicked
        ResultadoTXT.setText("" + objCalculadora.Resulado(ResultadoTXT.getText()));
    }//GEN-LAST:event_IgualBTNMouseClicked

    private void BorrarBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarBTNMouseClicked
        ResultadoTXT.setText("0");
        objCalculadora.Resulado(cero);
    }//GEN-LAST:event_BorrarBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarBTN;
    private javax.swing.JButton CeroBTN;
    private javax.swing.JButton CincoBTN;
    private javax.swing.JButton CuatroBTN;
    private javax.swing.JButton DividirBTN;
    private javax.swing.JButton DosBTN;
    private javax.swing.JButton IgualBTN;
    private javax.swing.JButton MultiplicarBTN;
    private javax.swing.JButton NueveBTN;
    private javax.swing.JButton OchoBTN;
    private javax.swing.JButton PuntoBTN;
    private javax.swing.JButton RestarBTN;
    private javax.swing.JTextField ResultadoTXT;
    private javax.swing.JButton SeisBTN;
    private javax.swing.JButton SieteBTN;
    private javax.swing.JButton SumarBTN;
    private javax.swing.JButton TresBTN;
    private javax.swing.JButton UnoBTN;
    // End of variables declaration//GEN-END:variables
}
